### ISSUE TITLE
How to show just the current directory instead of entire path?

### ISSUE THREAD

**Issue by mez** [agnoster/agnoster-zsh-theme#19]
Hey @agnoster,

Wondering where I can make a change to just show the current directory instead of the entire path?

Any hints would be great!

**Comment by Kapulara** [comment]
In: ~/.oh-my-zsh/themes/agnoster.zsh-theme

Change the function: 

```
# Dir: current working directory
prompt_dir() {
  prompt_segment blue black '%~'
}
```

to

```
# Dir: current working directory
prompt_dir() {
  prompt_segment blue black '%c'
}
```

It should be down somewhere at the bottom.

If you wan't to learn more about what you can use here take a look at [https://linux.die.net/man/1/zshmisc](url) or `man zshmisc` (find %C / %c)

**Comment by ohader** [comment]
Just for the records (since I had a similar problem):
https://github.com/robbyrussell/oh-my-zsh/wiki/Customization

**Comment by seemcat** [comment]
Hi, for some reason @Kapulara's answer did not work for me. I've been trying to make it so that instead of seeing the `maricrisbonzo@Maricriss-Macbook-Pro-2`, I only see the current directory. I am using .zshrc as well as .hyper:
<img width="405" alt="screen shot 2018-12-06 at 4 48 06 pm" src="https://user-images.githubusercontent.com/11692241/49620706-f82dac00-f976-11e8-82c9-fcab40088860.png">
Can someone please help?

**Comment by agnoster** [comment]
@seemcat Note that the answer above is just for showing the current _directory_ instead of the whole path - to hide the `user@host` part of the prompt, you need to specify a `DEFAULT_USER` (essentially, this part of the prompt appears to let you know if you're a different user from your usual one). So if your default username is `maricrisbonzo`, then just add the line

`export DEFAULT_USER="maricrisbonzo"`

to your `.zshrc` or wherever you prefer (I have most of my global config for my user in `.profile`)

(This is probably the design decision I'm least happy with in the prompt since it requires active configuration to "do the right thing", and I would be delighted to find a better solution - I'm thinking perhaps if no DEFAULT_USER is specified the username simply shouldn't be part of the prompt at all?)

**Comment by lloydXmas** [comment]
> Hi, for some reason @Kapulara's answer did not work for me. I've been trying to make it so that instead of seeing the `maricrisbonzo@Maricriss-Macbook-Pro-2`, I only see the current directory. I am using .zshrc as well as .hyper:
> <img alt="screen shot 2018-12-06 at 4 48 06 pm" width="405" src="https://user-images.githubusercontent.com/11692241/49620706-f82dac00-f976-11e8-82c9-fcab40088860.png">
> Can someone please help?

You can remove the `user@ hostname` portion of the prompt by commenting out a line in the `prompt_context()` function from  ~/.oh-my-zsh/themes/agnoster.zsh-theme
```
prompt_context() {
  local user=`whoami`

  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CONNECTION" ]]; then
    prompt_segment $PRIMARY_FG default " %(!.%{%F{yellow}%}.)$user@%m "
  fi
}
```

Comment the `prompt_segment` line, like so:

```
prompt_context() {
  local user=`whoami`

  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CONNECTION" ]]; then
    #prompt_segment $PRIMARY_FG default " %(!.%{%F{yellow}%}.)$user@%m "
  fi
}
```
The run `source ~/.zshrc` (or restart the terminal)

**Comment by CGS-Jack-Bashford** [comment]
@seemcat The simplest way to do what you're asking is to add this line to the top of your `.zshrc`:

```
DEFAULT_USER=$USER
```

**Comment by ghost** [comment]
i'm problem... help

➜  ~ ls -a
.              .bashrc      .motd_shown                .wget-hsts                      .zshrc
..             .cache       .oh-my-zsh                 .zcompdump                      .zshrc.pre-oh-my-zsh
.bash_history  .dir_colors  .profile                   .zcompdump-DESKTOP-H0FQA1E-5.8  gnome-terminal
.bash_logout   .landscape   .sudo_as_admin_successful  .zsh_history
➜  ~ cd .zshrc
cd: not a directory: .zshrc
➜  ~

**Comment by crowrish** [comment]
@eliseuTarGz `.zshrc` is a file, not a directory. I think the path you should go into is `.oh-my-zsh`.
Go to the path `.oh-my-zsh/themes` and open your theme file and edit `prompt_text()`.

**Comment by ahmed-hdeawy** [comment]
step 1. open your `.zshrc` file by `vim .zshrc`

step 2. go to the end of your file.

Paste this code:

```
prompt_dir() {
  prompt_segment blue $CURRENT_FG '%c'
}
```

**Comment by ruimartinsptl** [comment]
If you want to see also the last 3 parent directories, you can write:
```text
prompt_dir() {
  prompt_segment blue $CURRENT_FG '%3~'
}
```

where the `3` in `%3~` is the number of directories

Example:
<img width="331" alt="Screenshot 2022-06-18 at 02 35 35" src="https://user-images.githubusercontent.com/2766648/174417420-a4ac9bc4-6ecc-4b89-b510-28c270493b5c.png">

**Comment by Sultanc** [comment]
i used "%1c" to show only the current folder i am inside

**Comment by Davo00** [comment]
> %c
> 
> %.
> 
> %C
> 
> Trailing component of $PWD. An integer may follow the '%' to get more than one component. Unless '%C' is used, tilde contraction is performed first. These are deprecated as %c and %C are equivalent to %1~ and %1/, respectively, while explicit positive integers have the same effect as for the latter two sequences.

[https://linux.die.net/man/1/zshmisc](https://linux.die.net/man/1/zshmisc)

Looks like %c is deprecated, I have used `%2~` as described in the docs and mentioned by @ruimartinsptl

**Comment by andrewzjut** [comment]
> bartvanvliet

it works
