### ISSUE TITLE
Arrows appear to be broken

### ISSUE THREAD

**Issue by AlecThomson** [agnoster/agnoster-zsh-theme#68]
I'm using iTerm 2 on OSX + Solarized Dark. I find that the arrows do not line up with the text bars and that some colours (e.g. Github arrows) are broken. See below:
![screen shot 2018-02-13 at 4 07 38 pm](https://user-images.githubusercontent.com/9074527/36134658-4dd5afda-10da-11e8-95d7-1e7bf0c3f42a.png)

**Comment by griiid** [comment]
You can enter `Preferences/Profiles/Window`, and check `Keep background colors opaque`, it's right below `Transaprency` bar.

**Comment by AlecThomson** [comment]
My background is already fully opaque, so the `Keep background colors opaque` option is already ticked. How would this option change the appearance of the arrows?

**Comment by griiid** [comment]
Hmm... since ur setting is fully opaque, its not the answer.

Here's another try, `Preferences/Profiles/Colors`, the `Minimum constrast` bar, my setting is as below:
<img width="1030" alt="2018-02-15 5 11 51" src="https://user-images.githubusercontent.com/17796098/36248703-544c5360-1273-11e8-968b-6e590bdb1014.png">

When I drag it, it became:
<img width="1022" alt="2018-02-15 5 17 17" src="https://user-images.githubusercontent.com/17796098/36248939-24b649b6-1274-11e8-9633-640c93491377.png">

If I drag more, it became:
<img width="1022" alt="2018-02-15 5 17 32" src="https://user-images.githubusercontent.com/17796098/36248943-2b481688-1274-11e8-9985-94605f8c9156.png">

**Comment by AlecThomson** [comment]
Perfect! That fixed it. Thanks so much.
